-- developer
CREATE  ROLE developer COMMENT = 'creating for testing purpose' ;
-- snowday_db
CREATE  WAREHOUSE snowday_db WITH WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = XSMALL
MAX_CLUSTER_COUNT = 1
MIN_CLUSTER_COUNT = 1
SCALING_POLICY = STANDARD
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = FALSE
RESOURCE_MONITOR = NULL
COMMENT = 'Creating for demo purpose'
ENABLE_QUERY_ACCELERATION = FALSE
QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8 ;
