-- test_tbl112
CREATE   TABLE DEMO_127.DEMO.test_tbl112 (c1 varchar,
c2 varchar) COMMENT = 'test table1';
-- test_seq_112
CREATE  SEQUENCE DEMO_127.DEMO.test_seq_112 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
-- ff_csv
CREATE  FILE FORMAT DEMO_127.DEMO.ff_csv TYPE = csv COMPRESSION = AUTO
FIELD_DELIMITER = ',' 
SKIP_HEADER = 1
SKIP_BLANK_LINES = TRUE;
-- tst_stg_112

            CREATE   STAGE DEMO_127.DEMO.tst_stg_112
            ENCRYPTION = (TYPE = 'Snowflake_Full')
            DIRECTORY = (ENABLE = True REFRESH_ON_CREATE = True)
            COPY_OPTIONS = (ON_ERROR =ABORT_STATEMENT
PURGE = TRUE
RETURN_FAILED_ONLY = TRUE)
            FILE_FORMAT='DEMO_127.DEMO.MYCSV'
            
