-- dr_snowday_role1
CREATE  ROLE DR_SNOWDAY_ROLE1  ;
-- dr_snowday_tbl
ALTER TABLE DR_SNOWDAY_DB.DR_SNOWDAY_SCH.DR_SNOWDAY_TBL RENAME TO DR_SNOWDAY_DB.DR_SNOWDAY_SCH.Demo_Snowday;
-- dr_seq
DROP SEQUENCE APR3.TESTAPR3.DR_SEQ;
