-- dec_30
CREATE   DATABASE Dec_30  DATA_RETENTION_TIME_IN_DAYS =5
MAX_DATA_EXTENSION_TIME_IN_DAYS = 90
COMMENT = 'Dec30';
-- december_last
CREATE   SCHEMA DECEMBER_LAST.sch_30  DATA_RETENTION_TIME_IN_DAYS = 10
MAX_DATA_EXTENSION_TIME_IN_DAYS = 90
COMMENT = 'sch30';
-- tbl_dec_30
CREATE   TABLE DEMO_127.DEMO.tbl_dec_30 (first varchar(255),
last varchar(255)
) COMMENT = 'tbl_dec_30';
