-- rl_snowday_role
CREATE  ROLE RL_snowday_role  ;
-- test_wh
ALTER WAREHOUSE test_wh suspend;
-- tbl_snowday
ALTER TABLE TECHINNOVATORS.SNOWDAY_SCH.TBL_SNOWDAY RENAME TO TECHINNOVATORS.SNOWDAY_SCH.TBL2_Snowday;
-- dr_seq
DROP SEQUENCE DR_SNOWDAY_DB.DR_SNOWDAY_SCH.DR_SEQ;
